apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: portfolio
resources:
  - 10-kafka.yaml
  - 20-supportdesk-backend.yaml
  - 25-supportdesk-workers.yaml
  - 30-supportdesk-frontend.yaml
